### ISSUE TITLE
글 목록, 글 상세보기 기능 구현

### ISSUE THREAD

**Issue by wlsgml0229** [skarbgud/TodayWorker#18]
더보기 > 이후 글목록 구현
- 글목록에서 하나의 글 카드에서 일정 글자가 넘어가면 (.....)처리를 해야함   o
- infinite scroll(무한 스크롤) [일단 우선순위 후순위로 - 백엔드 어느정도 되서 글목록 `불러올수` 있을때] x

글 상세보기
- Breadcrumb x
- 제목  o
- 지역(ex. 서울시 동작구, 수원시 영통구) o
- 아이디 o
- 글쓴시간 o
- 조회수 o
- 댓글수 o
- 북마크 o
- 팔로우 (유저를 팔로우) o
- ... -> 링크복사 x
- 본문내용 o 
- 좋아요버튼 o
- 댓글수 o
- 공유버튼들(카카오,페이스북....) o
- 해시태그 o
- 댓글창 △ -> 카메라 넣는거 구현 (김진희)
- 대댓글 o
- 댓글 더보기 o
[[[[[[[[Dummy Data]]]]]]]]]

edit by 2021/08/21

**Comment by skarbgud** [comment]
대댓글, 댓글 더보기 -> 남규형

**Comment by skarbgud** [comment]
- ... -> 링크복사 , 신고
- 좋아요버튼(아이콘)
- 해시태그 (컴포넌트 -> 부트스트랩 태그로 변경)
- 댓글창 △ -> 카메라 넣는거 구현 -> 댓글에 이미지 추가 구현
- 댓글, 대댓글 width  조정 

edit by 2021/09/04
