### ISSUE TITLE
BE - ES와 RDB에 Board 데이터 관리

### ISSUE THREAD

**Issue by humanitas03** [skarbgud/TodayWorker#26]
### 수정 작업
* Spring data ElasticSearch의 ElasticSearchRepository를 이용해서 Elastic Search를 다루도록 기존 로직 변경

### 신규 작업
* Board - Reply Jpa Entity 추가 설계 구현
* ES 동기화 하는 부분은 Domain Event Listener로 삽입시 구현
  -> 수정이나 삭제에 대한 처리는 별도 요건 정의가 필요

### check-list
* 지금 FE에서 board 조회시 받는 Field들이 어떤게 있고, ES에 적재되어 있는 Document의 format 확인이 필요합니다.
* 그게 확인이 안되면 BoardVO 클래스에 정의된 기준으로 ES와 DB Table 스키마를 맞추겠습니다.

**Comment by skarbgud** [comment]
기존 데이터에 대한 POSTMAN 결과 공유합니다.
https://www.notion.so/BE-postman-b7cbb94605d64491b1875476c7db51ca

**Comment by humanitas03** [comment]
필드 맞추는 작업은 다른 티켓으로 추가 작업 진행하겠습니다.
