### ISSUE TITLE
[BE] Paging 

### ISSUE THREAD

**Issue by humanitas03** [skarbgud/TodayWorker#35]
```/board/get-board-list.do``` 호출 시 스크롤을 끝까지 내려도 DB에 적재된 모든 페이지를 보여주지 않는 현상

원인 : FE에서 기대하는 다음 페이지 시작 점(fromIndex)과 서버에서 받아서 처리하는 페이지 시작점(pageIndex)간에 오해
 * FE :   fromIndex를 다음 시작되는 페이지의 첫번째 인덱스, 10번째 페이지에서는 fromIndex가 100
 * BE : fromIndex를 pageIndex로 넣어줌. 즉, 1000개 글을 한 페이지에 10건씩 뿌려준다고 하면 총 1000 / 10 = 100 의 pageIndex

조치 : 일단 서버에서 맞춰 주도록 수정을 하겠습니다. 다만, 지금 `앞으로 서버에 페이징 처리가 필요한 요청에 대해서 FE에서는 지금과 같은 방식(fromIndex, PageSize)으로 요청이 오는걸로 픽스가 되는 건지 확인이 필요합니다.

> DB 저장된 글은 1,000개 이지만, 실제로 100개의 게시글만 뿌려주는 것으로 보임(pagesize가 10이면 100번 호출이 있어야 하는데 10번만 호출하고 끝남)
![image](https://user-images.githubusercontent.com/16380977/151097319-bc873096-ec10-4ef5-84c6-757e4064cc27.png)

> fromIndex를 서버에서 PageOffset(pageIndex)로 넣어서 실제로 0~9번째 게시글 다음으로 100번째 ~ 109번째 인덱스에 해당하는 게시글이 내려가고 있음.
![image](https://user-images.githubusercontent.com/16380977/151098237-c59498dd-ffaa-44eb-bfe6-1db74fcc2a59.png)

**Comment by humanitas03** [comment]
수정 후 
![image](https://user-images.githubusercontent.com/16380977/151099841-815a1b15-c16a-4ca5-8f7b-2041fec8f22b.png)

**Comment by skarbgud** [comment]
> 앞으로 서버에 페이징 처리가 필요한 요청에 대해서 FE에서는 지금과 같은 방식(fromIndex, PageSize)으로 요청이 오는걸로 픽스가 되는 건지 확인이 필요

별다른 이견 없으면 페이징 처리 방식을 이대로 가는것으로 하겠습니다. (34e2919e78542a595b61dabc1eaaaf979eb2775e)
